package:
  name: fms_yaml_tools

source:
  path: .

build:
  script: 
    - {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

channels:
    - defaults
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - click
    - pyyaml
    - pylint
    - jsonschema

test:
  source_files:
    - fms_yaml_tools/
  commands:
	- python -m unittest discover -s test

about:
  home: https://github.com/NOAA-GFDL/fms_yaml_tools