name: build_conda
on:
  [push]
#  pull_request:
#    branches:
#      - FOOmainBAR


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v4
    - name: Run Conda to Build
      run: |
        conda config --append channels conda-forge
        conda config --append channels noaa-gfdl
        conda install conda-build conda-verify
        git submodule update --init --recursive --remote
        conda build .
        ls .
